WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT    = _{ "#" ~ (!NEWLINE ~ ANY)* }

KEYWORD = @{ "fn" | "if" | "else" | "while" | "for" | "in" | "true" | "false" | "return" | "@macro" }

Identifier = @{ !KEYWORD ~ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

Program = _{ SOI ~ Stmt* ~ EOI }

Stmt       =  { Function | SimpleStmt }
SimpleStmt = _{ (Return | Assignment | Expr) }

Function =  { "fn" ~ Identifier ~ "(" ~ Params? ~ ")" ~ Block }
Params   = _{ Identifier ~ ("," ~ Identifier)* }

Block = { "{" ~ Stmt* ~ "}" }

Return = { "return" ~ Expr }

Assignment = { Identifier ~ "=" ~ Expr }

Expr = { Conditional | WhileLoop | ForLoop | Comparison }

Conditional = { "if" ~ "(" ~ Expr ~ ")" ~ Block ~ "else" ~ Block }

WhileLoop = { "while" ~ "(" ~ Expr ~ ")" ~ Block }
ForLoop   = { "for" ~ Identifier ~ "in" ~ Expr ~ ".." ~ Expr ~ Block }

Comparison = { Additive ~ (CompOp ~ Additive)* }
CompOp     = { "<=" | ">=" | "<" | ">" | "==" | "!=" }

Additive = { Multiplicative ~ (AddOp ~ Multiplicative)* }
AddOp    = { "+" | "-" }

Multiplicative = { Unary ~ (MulOp ~ Unary)* }
MulOp          = { "*" | "/" | "%" }

Unary   = { UnaryOp ~ Unary | Call }
UnaryOp = { "-" | "!" }

Call     =  { Primary ~ CallArgs* }
CallArgs =  { "(" ~ Args? ~ ")" }
Args     = _{ Expr ~ ("," ~ Expr)* }

Primary = _{ Literal | Identifier | "(" ~ Expr ~ ")" }

Literal =  { Bool | Int }
Int     = @{ ASCII_DIGIT+ }
Bool    = @{ "true" | "false" }
