
WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT    = _{ "#" ~ (!NEWLINE ~ ANY)* }

KEYWORD = @{ "def" | "if" | "else" | "while" | "true" | "false" | "return" | "int" | "bool" }

Identifier = @{ !KEYWORD ~ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

Type     = { IntType | BoolType }
IntType  = { "int" }
BoolType = { "bool" }

Program = _{ SOI ~ Stmt* ~ EOI }

Stmt       =  { Function | SimpleStmt }
SimpleStmt = _{ (Return | Assignment | Expr) }

Function    =  { "def" ~ Identifier ~ "(" ~ TypedParams? ~ ")" ~ ReturnType? ~ Block }
TypedParams = _{ TypedParam ~ ("," ~ TypedParam)* }
TypedParam  =  { Identifier ~ ":" ~ Type }
ReturnType  =  { "->" ~ Type }

Block = { "{" ~ Stmt* ~ "}" }

Return = { "return" ~ Expr }

Assignment = { Identifier ~ (":" ~ Type)? ~ "=" ~ Expr }

Expr = { Conditional | WhileLoop | Comparison }

Conditional = { "if" ~ "(" ~ Expr ~ ")" ~ Block ~ "else" ~ Block }

WhileLoop = { "while" ~ "(" ~ Expr ~ ")" ~ Block }

Comparison = { Additive ~ (CompOp ~ Additive)* }
CompOp     = { "<=" | ">=" | "<" | ">" | "==" | "!=" }

Additive = { Multiplicative ~ (AddOp ~ Multiplicative)* }
AddOp    = { "+" | "-" }

Multiplicative = { Unary ~ (MulOp ~ Unary)* }
MulOp          = { "*" | "/" | "%" }

Unary   = { UnaryOp ~ Unary | Call }
UnaryOp = { "-" | "!" }

Call     =  { Primary ~ CallArgs* }
CallArgs =  { "(" ~ Args? ~ ")" }
Args     = _{ Expr ~ ("," ~ Expr)* }

Primary = _{ Literal | Identifier | "(" ~ Expr ~ ")" }

Literal =  { Bool | Int }
Int     = @{ ASCII_DIGIT+ }
Bool    = @{ "true" | "false" }
